# Generated by Django 4.2.7 on 2023-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
