# Generated by Django 4.2.7 on 2023-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_card_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_fav',
            field=models.BooleanField(),
        ),
    ]
