# Generated by Django 4.2.7 on 2023-11-17 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_alter_card_is_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='card',
            name='users_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorite_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
