# Generated by Django 4.2.7 on 2023-12-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_card_is_fav_remove_card_users_favorited_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
